config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :services do
    # member do
    #   get 'publish'
    # end 
    # member do
    #   get 'unpublish'
    # end 
    resources :comments
  end
  
  root 'main#index'
end

app/controllers/main_controller.rb
class MainController < ApplicationController    
  def index
  	@services = Service.published.order(:created_at).limit(4)
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<!-- test -->
<div class="intro" style="background-image: url(<%= asset_path 'bg3.jpg' %>);">
  <section class="intro-header">
  	<div class="jumbotron">
  	  <h1 class="text-center">¿Que buscas en Linares?</h1>
  	  <p class="text-center">Si quieres ver todos los anuncios, haz click en buscar</p>
  	  <section class="row">
  	  	<section class="col-md-6 col-md-offset-3">
              <%= form_tag services_path, :method => 'get', class: "input-group input-group-lg" do %>
                <%= text_field_tag "input_search", nil, class: 'form-control' %>
                <span class="input-group-btn ">
                  <%= submit_tag "Buscar", class: "btn btn-primary" %>
                </span>
              <% end %>
  	  	</section>
  	  </section>
  	</div>
  </section>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="row">
          <% @services.each do |service| %>
              <div class="col-sm-3 col-lg-3 col-md-3">
                  <div class="thumbnail">
                      <%= image_tag service.try(:photo), class: 'img-search' %>
                      <div class="caption">
                          <h4><%= link_to truncate(service.title, length: 19), service_path(service) %></h4>
                          <p><%= truncate(service.description, length: 150) %></p>

                      </div>
                      <div class="ratings">
                          <p class="pull-right"><%= service.visit_count%> visitas</p>
                          <span><%= service.comments.count(:vote)%> veces calificado</span>                          
                      </div>
                  </div>
              </div>
          <% end %>
        </div>
    </div>
</div>

<script>
    var tags = <%= Service.order(:title).published.map(&:title).to_json.html_safe %>

    $( "#input_search" ).autocomplete({
      source: tags
    });

    $('#stars').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      }
    });
</script>