config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :services do
    # member do
    #   get 'publish'
    # end 
    # member do
    #   get 'unpublish'
    # end 
    resources :comments
  end
  
  root 'main#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :services
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_sidebar.html.erb
<div class="list-group">
    <% @categories.each do |category| %>
        <%= link_to category, class: 'list-group-item' do %>
		   <%= category.name %> <span class="badge"><%= category.services.published.size %></span>
		<% end %>
    <%end%>
</div>

app/views/categories/show.html.erb
<div class="row">
    <div class="col-md-3">
      <%= render 'categories/sidebar' %>
    </div>

    <div class="col-md-9">
        <div class="row">
          <% @category.services.published.each do |service| %>
              <div class="col-sm-4 col-lg-4 col-md-4">
                  <div class="thumbnail">
                  
                      <%= image_tag service.photo, class: 'img-search' %>
                      <div class="caption">
                          <h4><%= link_to truncate(service.title, length: 19), service_path(service) %></h4>
                          <p><%= truncate(service.description, length: 150) %></p>

                      </div>
                      <div class="ratings">
                          <p class="pull-right"><%= service.visit_count%> visitas</p>
                          <span><%= service.comments.count(:vote)%> veces calificado</span>
                      </div>
                  </div>
              </div>
          <% end %>
        
            <div class="col-sm-4 col-lg-4 col-md-4">
                <h4><%= link_to '¿Quieres subir tu servicios?', new_service_path%></a></h4>
                <p>Anunciarte en servicios en un click es muy facil, solo tienes que hacer click en el boton de abajo</p>
                <%= link_to 'Subir Anuncio', new_service_path, class: 'btn btn-primary'%>
            </div>
        </div>
    </div>
</div>